name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.36
          sudo apt update
          sudo apt install -y openjdk-8-jdk zip unzip
      - name: Build APK
        run: |
          buildozer init
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: bin/*.apk
